### ISSUE TITLE
Purpose of this library?

### ISSUE THREAD

**Issue by mrseth** [Teamweek/instadate#4]
What does it offer that I couldn't get from the standard date  [API](http://www.w3schools.com/jsref/jsref_obj_date.asp)?

**Comment by herkyl** [comment]
Default Date API offers only millisecond based date comparisons, calculations and manipulations. Just check the Instadate API vs Date API, they are completely different.

**Comment by mrseth** [comment]
So your library just multiplies MS by X?

**Comment by herkyl** [comment]
Not really.. Please take a look at the API docs for an overview of everything this library does
