### ISSUE TITLE
use `files` property in package.json

### ISSUE THREAD

**Issue by SamVerschueren** [Teamweek/instadate#5]
Use the [files](https://docs.npmjs.com/files/package.json#files) property in `package.json` and include `instadate.js`. When a user installs this as dependency, the tests are not installed as well.

Nice library btw :).

**Comment by herkyl** [comment]
Thanks! Fixed in https://github.com/Teamweek/instadate/commit/396cb1d87b466aa8907c73dcdf484a98ebc538da
