### ISSUE TITLE
Holidays?

### ISSUE THREAD

**Issue by vzvenyach** [Teamweek/instadate#8]
This may be a feature that adds too much complexity, but it would be _nice_ if the library included holidays, whether as a plugin or otherwise.

**Comment by herkyl** [comment]
Hey! Could give me some examples on how you would see this working?

**Comment by vzvenyach** [comment]
Take, e.g., the `workDaysInPeriod`. It would be cool if I could add a parameter that would _also_ exclude holidays, like so:

`workDaysInPeriod(firstDay, length, holidays=us)`

or something along those lines...

**Comment by herkyl** [comment]
I'm afraid that a JSON file containing all world holidays would be a lot bigger then Instadate itself. This would go out of scope (as you said).

If you already have a list of holidays you could use `instadate.dates(from, to)` or `instadate.isDayBetween(holiday, start, end)`
